version: '3.8'

services:
    app:
        build: .
        ports:
            - '8080:8000' # FastAPI
            - '3001:3000' # Веб-интерфейс
        environment:
            - PYTHONUNBUFFERED=1
        env_file:
            - .env
        healthcheck:
            test: curl --fail http://localhost:8000/docs || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 15s
        restart: unless-stopped
