version: '3.8'

services:
    app:
        build: .
        ports:
            - '8080:8000' # FastAPI
        environment:
            - PYTHONUNBUFFERED=1
            - HOST=0.0.0.0
            - PORT=8000
        env_file:
            - .env
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000/docs']
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 5s
        volumes:
            - ./src:/app/src
            - ./.env:/app/.env
        restart: unless-stopped
        networks:
            - pkg_network

networks:
    pkg_network:
        driver: bridge
