version: '3.8'

services:
    app:
        build: .
        ports:
            - '8080:8000' # FastAPI
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - ./src:/app/src
        restart: unless-stopped
        networks:
            - pkg_network

networks:
    pkg_network:
        driver: bridge
